### ISSUE TITLE
Support Multiple Tests in one run 

### ISSUE THREAD

**Issue by mattthaber** [tophat/sanity-runner#170]
Due to how AfterEach() is setup, it closes the browser after a single test is ran, this prevents a scenerio of running multiple tests in one file from ever occuring.

BeforeEach/AfterEach should be setup in a way that the browser is closed only after all tests are ran.

**Comment by noahnu** [comment]
To simplify the runner, we're only going to support 1 test case per run. If we want to support multiple runs per lambda, we could look at parallelizing the requests in the service to re-use a service.
