### ISSUE TITLE
GitHub workflow fails occasionally due to ECR datadog rate limiting

### ISSUE THREAD

**Issue by noahnu** [tophat/sanity-runner#325]
Perhaps we can do better caching? The image doesn't change often.

https://github.com/tophat/sanity-runner/runs/7692655244?check_suite_focus=true

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1297096/185630806-fa4ab7e4-e5b8-45fc-813f-bb347f1b0d85.png">

**Comment by shawndrape** [comment]
Is it always the copy specifically that is rate limited, or is it the use of the `public.ecr.aws` generally?

We should be able to publish this to Docker Hub under an open source account so we don't have to build it off AWS each run if that's the concern.

**Comment by noahnu** [comment]
It's the COPY from ECR because that step downloads from ECR. Maybe datadog publishes a non-ecr version.

**Comment by noahnu** [comment]
Closing this for now, might have solved it with the better caching.
