### ISSUE TITLE
Parameterize configuration

### ISSUE THREAD

**Issue by mhaber-tophat** [tophat/sanity-runner#5]
Support a config file inside of relying on passing in as flags. Ideally the config could just be a yaml template? Probably the easiest 

Config should support the following....

- lambda-function
- output-dir
- test-dir
- custom vars

**Comment by mhaber-tophat** [comment]
File could be found under /etc/sanity-runner/config.yml ? 

Or passed in via a flag --config-file <filename>

**Comment by mhaber-tophat** [comment]
default values could be...?

output-dir: /opt/sanity-runner/output
test-dir: /opt/sanity-runner/tests

**Comment by eastenluis** [comment]
I'm leaning towards not setting a default path for the config file. It seems an extra dependency if users want to use flags only. 
I'm not sure about the output-dir or test-dir...Personally I prefer the way `jest` does, which reads all files recursively in current directory by default. This can be something to consider in the test file pattern issue.

**Comment by eastenluis** [comment]
Added `--config` flag which accepts an json config file.
