### ISSUE TITLE
Support Referencing chrome via URL.

### ISSUE THREAD

**Issue by mhaber-tophat** [tophat/sanity-runner#6]
Currently the headlessChrome used needs to committed into the repo, would be nice if we could reference a url and have deploy upload to your s3 bucket.

**Comment by mhaber-tophat** [comment]
Tricky part here is making sure puppeteer version lines up with chrome we are using

**Comment by shawndrape** [comment]
Before adding this support, going to try and get a build working with the latest serverless chrome and puppeteer pair
